# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-10 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='lock_to_studnet',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='board',
            name='lock_to_testtakcer',
            field=models.BooleanField(default=False),
        ),
    ]
